language: java
notifications:
    email:
        - markus.sabadello@gmail.com
branches:
    only:
        - master
jdk:
    - openjdk6
    - oraclejdk6
    - openjdk7
    - oraclejdk7
install: mvn install -DskipTests=true
script: mvn clean integration-test
