language: java
notifications:
    email:
        - markus@projectdanube.org
branches:
    only:
        - master
git:
    depth: 10
jdk:
    - openjdk6
    - openjdk7
    - oraclejdk7
    - oraclejdk8
install: mvn install -DskipTests=true
script: mvn clean integration-test
